### ISSUE TITLE
undetermined?

### ISSUE THREAD

**Issue by chenyj8** [KennthShang/PhaTYP#1]
Hello,

Thanks for the excellent tool. Is it possible that the life styles of some viral contigs are undetermined (absence in the output csv file)?

**Comment by KennthShang** [comment]
Yes, some contigs might not exist in the final csv file, which means there is no sufficient evidence for prediction.

BTW, you can also reject some contigs by setting a threshold for the score in prediction.csv

**Comment by chenyj8** [comment]
What is the default threshold?

**Comment by KennthShang** [comment]
We did not use the threshold in the program and paper. 

But based on my previous experiences, I suggest using the quartiles as the threshold (which will be < 0.25 and > 0.75). 

In fact, it depends on how many contigs you would like to output a result.
