### ISSUE TITLE
Viruses with alternative genetic codes

### ISSUE THREAD

**Issue by asierFernandezP** [KennthShang/PhaTYP#3]
Hi!

Thanks for the great tool! I was wondering whether you are planning to update the current version of prodigal used by PhaTYP to prodigal-gv to improve gene calling for viruses with alternative genetic codes.

Best,

Asier

**Comment by KennthShang** [comment]
Hi,

Thanks for using our tool. We have just released the new version for your request. 

We added a parameter called 'prodigal' for you to use different versions of the prodigal. You can use the path of your prodigal. Or if you have added your prodigal into your env path, you can use the path's name.

For example:

```
python preprocessing.py --contigs test_contigs.fa --prodigal prodigal-gv
```

**Comment by asierFernandezP** [comment]
Thank you for your quick answer and update!

I already tested it and works perfectly fine :)
