### ISSUE TITLE
Error creating DIAMOND database

### ISSUE THREAD

**Issue by asierFernandezP** [KennthShang/PhaTYP#4]
When testing the tool with the test_contigs.fa file, I get the following error when it tries to build the DIAMOND database:

---------------------------------Diamond BLASTp---------------------------------
Creating Diamond database and running Diamond...
Creating Diamond database...
create database failed

I have tried installing different versions of DIAMOND (2.0.13, 4.0.515) but I get the same error. Which is the version you recommend?

Thanks!

**Comment by KennthShang** [comment]
Hi,

Did you follow the guidelines and install the env?

```
cd PhaTYP/
conda env create -f phatyp.yaml -n phatyp
conda activate phatyp
cd database/
bzip2 -d database.fa.bz2
cd ..

fileid="1tsUArctGf9Fd3xa-0sEcp6ykwxTy9uxG"
filename="model.zip"
html=`curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}"`
curl -Lb ./cookie "https://drive.google.com/uc?export=download&`echo ${html}|grep -Po '(confirm=[a-zA-Z0-9\-_]+)'`&id=${fileid}" -o ${filename}

unzip model.zip
```


If you decide to install by yourself, please try diamond=0.9.14

Best,
Jiayu

**Comment by asierFernandezP** [comment]
Thank you, I did not not see that the diamond version is already specified in the phatyp.yaml file. In this case I installed  PhaTYP using a Python virtual environment instead of the conda environment, so I built a requirements.txt file with the version of the packages to install. And apparently, it also works with DIAMOND=2.0.13 (at least for the test_contigs.fa that you provide).

**Comment by KennthShang** [comment]
If you build the env by yourself, you need to run the codes below before running PhaTYP:
```
cd database/
bzip2 -d database.fa.bz2
cd ..

fileid="1tsUArctGf9Fd3xa-0sEcp6ykwxTy9uxG"
filename="model.zip"
html=`curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}"`
curl -Lb ./cookie "https://drive.google.com/uc?export=download&`echo ${html}|grep -Po '(confirm=[a-zA-Z0-9\-_]+)'`&id=${fileid}" -o ${filename}

unzip model.zip
```

Best,
Jiayu

**Comment by asierFernandezP** [comment]
Yes, I did it and it works! 

Thank you :)

**Comment by KennthShang** [comment]
Good to know.
