### ISSUE TITLE
Error opening the database

### ISSUE THREAD

**Issue by asierFernandezP** [KennthShang/PhaTYP#6]
HI,

I get the following error when running PhaTYP:

```
Opening the database file... No such file or directory
 [0.004s]
Error: Error calling stat on file database/database.fa
Running prodigal-gv...


---------------------------------Diamond BLASTp---------------------------------
Creating Diamond database and running Diamond...
Creating Diamond database...
create database failed
Traceback (most recent call last):
  File "/data/umcg-llnext/python_venvs/PhaTYP_venv/PhaTYP/PhaTYP.py", line 37, in <module>
    id2contig = pkl.load(open(f'{transformer_fn}/sentence_id2contig.dict', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'phatyp//sentence_id2contig.dict'
```

Do I need to add the location of the database to the path? Or is there any options/flags to add the database path when running the`preprocessing.py` script?

**Comment by KennthShang** [comment]
Did you unpack the database (following the guidelines)

     bzip2 -d database.fa.bz2

**Comment by asierFernandezP** [comment]
Yes, the database is unpacked. When I run it from the directory where the "database"directory is present, it works. But not when I run it from a different directory.

**Comment by KennthShang** [comment]
The program in this GitHub can be run only within the folder. 

If you wish running outside the folder, you can check its application version: https://github.com/KennthShang/PhaBOX

or revise the code in preprocessing.py: line 74 to give the program a absolute path to the database.

**Comment by asierFernandezP** [comment]
Perfect! Thank you very much!
